# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileType', models.CharField(choices=[('coa', 'Chart of Accounts'), ('customers', 'Customers'), ('vendors', 'Vendors'), ('invoices', 'Invoices'), ('bills', 'Bills')], max_length=20)),
                ('File', models.FileField(upload_to='import_files/')),
                ('UploadedAt', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(default='pending', max_length=20)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RowNumber', models.IntegerField(null=True)),
                ('ErrorMessage', models.TextField()),
                ('ImportFileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='importer.importfile')),
            ],
            options={
                'verbose_name': 'Import Error',
                'verbose_name_plural': 'Import Errors',
                'db_table': 'ImportErrors',
            },
        ),
    ]
